WebApp/WebApp/Entities/Body.cs
using System.Collections.Generic;

namespace WebApp.Entities
{
    public class Body : Metadata
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Face> Faces { get; set; }
        public List<Line> Lines { get; set; }
        public List<Point> Points { get; set; }
    }
}

WebApp/WebApp/ViewModels/Bodies/BodyCreateRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.ViewModels.Bodies
{
    public class BodyCreateRequest
    {
        public string Name { get; set; }
     
        public string Description { get; set; }
    }
}

WebApp/WebApp/ViewModels/Bodies/BodyRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Enums;

namespace WebApp.ViewModels.Bodies
{
    public class BodyRequest
    {
        public LOD Lod { get; set; }

        public List<int> BodyId { get; set; }
    }
}

WebApp/WebApp/ViewModels/Bodies/BodyUpdateRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.ViewModels.Bodies
{
    public class BodyUpdateRequest
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    }
}

WebApp/WebApp/ViewModels/Bodies/BodyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.ViewModels.Faces;
using WebApp.ViewModels.Lines;
using WebApp.ViewModels.Points;

namespace WebApp.ViewModels.Bodies
{
    public class BodyViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? CreatedAt { get; set; }

        public string UpdatedBy { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public List<FaceViewModel> Faces { get; set; }

        public List<LineViewModel> Lines { get; set; }

        public List<PointViewModel> Points { get; set; }
    }
}

WebApp/WebApp/Controllers/BodyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Services;
using WebApp.ViewModels.Bodies;

namespace WebApp.Controllers
{
    public class BodyController : Controller
    {
        private readonly IBodyService _bodyService;

        public BodyController(IBodyService bodyService)
        {
            _bodyService = bodyService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _bodyService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.isShow = false;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BodyCreateRequest model)
        {
            var res = await _bodyService.Create(model);
            ViewBag.isShow = true;
            ViewBag.isSuccess = res;

            if (res)
            {
                ViewBag.message = "Tạo body thành công";
                ModelState.Clear();

                return View();
            }
            else
            {
                ViewBag.message = "Tạo body không thành công";
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.isShow = false;
            return View(await _bodyService.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, BodyUpdateRequest model)
        {
            var res = await _bodyService.Update(id, model);
            ViewBag.isShow = true;
            ViewBag.isSuccess = res;

            if (res)
            {
                ViewBag.message = "Cập nhật body thành công";
            }
            else
            {
                ViewBag.message = "Cập nhật body không thành công";
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var res = await _bodyService.Delete(id);
             
            return Json(new
            {
                isSuccess = res
            });
        } 
    }
}

WebApp/WebApp/Views/Body/Create.cshtml
@using WebApp.ViewModels.Bodies;
@model BodyCreateRequest
 

<h1>Tạo Body</h1>
<hr />
<div class="row">
    <div class="col-md-10 mx-auto">
        <form asp-action="Create">

            @if (ViewBag.isShow)
            {
                <div class="alert alert-@(ViewBag.isSuccess?"success":"danger")" role="alert">
                    @ViewBag.message
                </div>
            }

            <div class="form-group row">
                <label class="control-label col-3"><strong>Tên body</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Name" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-3"><strong>Mô tả</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Description" class="form-control" required />
                </div>
                </div>

            <div class="form-group">
                <div class="w-100 text-center">
                    <input type="submit" value="Tạo mới" class="btn btn-primary w-50" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div> 

WebApp/WebApp/Views/Body/Edit.cshtml
@using WebApp.ViewModels.Bodies;
@model BodyUpdateRequest


<h1>Cập nhật Body</h1>
<hr />
<div class="row">
    <div class="col-md-10 mx-auto">
        <form asp-action="Edit">

            @if (ViewBag.isShow)
            {
                <div class="alert alert-@(ViewBag.isSuccess?"success":"danger")" role="alert">
                    @ViewBag.message
                </div>
            }
                    <input asp-for="@Model.Id" type="hidden" class="form-control" />

            <div class="form-group row">
                <label class="control-label col-3"><strong>Tên body</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Name" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-3"><strong>Mô tả</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Description" class="form-control" required />
                </div>
            </div>

            <div class="form-group">
                <div class="w-100 text-center">
                    <input type="submit" value="Cập nhật" class="btn btn-primary w-50" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div> 

WebApp/WebApp/Views/Body/Index.cshtml
@model List<WebApp.ViewModels.Bodies.BodyViewModel>

<h1>Danh sách các Body</h1>
<hr />
<div class="row">
    <div class="mx-auto">
        <div>
            <a class="btn btn-primary" asp-controller="Body" asp-action="Create">
                Tạo
            </a>
        </div>
        <table class="table caption-top mt-2">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Created by</th> 
                    <th scope="col">Updated by</th> 
                    <th scope="col">Modified</th>
                </tr>
            </thead>
            <tbody id="body-bodies">
                @{
                    var count = Model.Count;
                }
                @for (int i = 0; i < count; i++)
                {
                    var item = Model[i];
                    <tr>
                        <th scope="row">@(i+1)</th>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td><strong>@item.CreatedBy</strong></td> 
                        <td ><strong>@(string.IsNullOrEmpty(item.UpdatedBy)?"- - - - -": item.UpdatedBy)</strong></td> 
                        <td>
                            <div class="d-flex justify-content-center align-items-center">
                                <a class="btn btn-danger btn-delete-body" data-id="@item.Id">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                                <a class="btn btn-primary" asp-controller="Body" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="far fa-edit"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    const bodiesEle = document.getElementById('body-bodies')

    const updateId = () => {
        const trEles = bodiesEle.querySelectorAll('tr')

        trEles.forEach((item, i) => {
            var th = item.querySelector('th')
            th.innerText = i + 1
        })
    }

    $('body').on('click', '.btn-delete-body', function () {

        const pw = window.prompt("Password?")

        if (pw.toLocaleLowerCase() !== '1234567890') {
            return
        }

        if (confirm('Bạn có chắc chắn muốn xóa body?')) {
            if (confirm('Bạn có chắc chưa?')) {

                const id = $(this).data('id')

                $.ajax({
                    url: `/Body/Delete/${id}`,
                    success: (res) => {
                        if (res.isSuccess) {
                            $(this).parents('tr').remove();
                            updateId()

                            alert('Xóa thành công')
                        }
                    }
                });


            }
        }
    })


</script>