WebApp/WebApp/ViewModels/LineTypes/LineTypeCreateRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.ViewModels.LineTypeOptions;

namespace WebApp.ViewModels.LineTypes
{
    public class LineTypeCreateRequest
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public List<LineTypeOptionCreateRequest> LineTypeOptions { get; set; }
    }
}

WebApp/WebApp/ViewModels/LineTypes/LineTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.ViewModels.LineTypes
{
    public class LineTypeViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}

WebApp/WebApp/Controllers/LineTypeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Services;
using WebApp.ViewModels.LineTypes;

namespace WebApp.Controllers
{
    public class LineTypeController : Controller
    {
        private readonly ILineTypeService _lineTypeService;
        private readonly IOptionService _optionService;

        public LineTypeController(ILineTypeService lineTypeService,
            IOptionService optionService)
        {
            _lineTypeService = lineTypeService;
            _optionService = optionService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _lineTypeService.GetAll());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.isShow = false;
            ViewBag.options = await _optionService.GetAll();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(LineTypeCreateRequest model)
        {
            var res = await _lineTypeService.Create(model);
            ViewBag.isShow = true;
            ViewBag.isSuccess = res;
            ViewBag.options = await _optionService.GetAll();

            if (res)
            {
                ViewBag.message = "Tạo LineType thành công";
                ModelState.Clear();

                return View();
            }
            else
            {
                ViewBag.message = "Tạo LineType không thành công";
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.isShow = false;
            ViewBag.options = await _optionService.GetAll();
            return View(await _lineTypeService.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, LineTypeCreateRequest model)
        {
            var res = await _lineTypeService.Update(id, model);
            ViewBag.isShow = true;
            ViewBag.isSuccess = res;
            ViewBag.options = await _optionService.GetAll();

            if (res)
            {
                ViewBag.message = "Cập nhật LineType thành công";

                model = await _lineTypeService.GetById(id);
            }
            else
            {
                ViewBag.message = "Cập nhật LineType không thành công";
            }
             

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var res = await _lineTypeService.Delete(id);

            return Json(new
            {
                isSuccess = res
            });
        }
    }
}

WebApp/WebApp/Views/LineType/Create.cshtml
@using WebApp.ViewModels.LineTypes;
@using WebApp.ViewModels.Options;
@model LineTypeCreateRequest

@{
    var options = ViewBag.options as List<OptionViewModel>;
}

<h1>Tạo LineType</h1>
<hr />
<div class="row">
    <div class="col-md-10 mx-auto">
        <form asp-action="Create">

            @if (ViewBag.isShow)
            {
                <div class="alert alert-@(ViewBag.isSuccess?"success":"danger")" role="alert">
                    @ViewBag.message
                </div>
            }

            <div class="form-group row">
                <label class="control-label col-3"><strong>LineType name</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Name" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-3"><strong>Description</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Description" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-3"><strong>Options</strong></label>
                <div class="col-9">
                    <div class="row">
                        @for (int i = 0; i < options.Count; i++)
                        {
                        <div class="col-lg-3 mb-2">
                            <div class="d-flex justify-content-start align-items-start">
                                <input asp-for="LineTypeOptions[i].IsCheckd" class="form-control mr-2" type="checkbox" style="width:30px" />
                                <input asp-for="LineTypeOptions[i].OptionId" value="@options[i].Id" class="form-control mr-2" type="hidden" />
                                <label for="LineTypeOptions_@(i)__OptionId" style="cursor: pointer" class="mb-0 mt-1">@options[i].Name</label>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="w-100 text-center">
                    <input type="submit" value="Tạo mới" class="btn btn-primary w-50" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div> 

WebApp/WebApp/Views/LineType/Edit.cshtml
@using WebApp.ViewModels.LineTypes;
@using WebApp.ViewModels.Options;
@model LineTypeCreateRequest

@{
    var options = ViewBag.options as List<OptionViewModel>;
}

<h1>Cập nhật LineType</h1>
<hr />
<div class="row">
    <div class="col-md-10 mx-auto">
        <form asp-action="Edit">

            @if (ViewBag.isShow)
            {
                <div class="alert alert-@(ViewBag.isSuccess?"success":"danger")" role="alert">
                    @ViewBag.message
                </div>
            }
            <input asp-for="@Model.Id" type="hidden" class="form-control" required />

            <div class="form-group row">
                <label class="control-label col-3"><strong>LineType name</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Name" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-3"><strong>Description</strong></label>
                <div class="col-9">
                    <input asp-for="@Model.Description" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-3"><strong>Options</strong></label>
                <div class="col-9">
                    <div class="row">
                        @for (int i = 0; i < options.Count; i++)
                        {
                        <div class="col-lg-3 mb-2">
                            <div class="d-flex justify-content-start align-items-start">
                                <input asp-for="LineTypeOptions[i].IsCheckd" class="form-control mr-2" type="checkbox" style="width:30px" />
                                <input asp-for="LineTypeOptions[i].OptionId" value="@options[i].Id" class="form-control mr-2" type="hidden" />
                                <label for="LineTypeOptions_@(i)__OptionId" style="cursor: pointer" class="mb-0 mt-1">@options[i].Name</label>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="w-100 text-center">
                    <input type="submit" value="Cập nhật" class="btn btn-primary w-50" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div> 

WebApp/WebApp/Views/LineType/Index.cshtml
@model List<WebApp.ViewModels.LineTypes.LineTypeViewModel>

<h1>Danh sách các LineType</h1>
<hr />
<div class="row">
    <div class="mx-auto">
        <div>
            <a class="btn btn-primary" asp-controller="LineType" asp-action="Create">
                Tạo
            </a>
        </div>
        <table class="table caption-top mt-2">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Created by</th>
                    <th scope="col">Updated by</th>
                    <th scope="col">Modified</th>
                </tr>
            </thead>
            <tbody id="body-bodies">
                @{
                    var count = Model.Count;
                }
                @for (int i = 0; i < count; i++)
                {
                    var item = Model[i];
                    <tr>
                        <th scope="row">@(i+1)</th>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td><strong>@item.CreatedBy</strong></td>
                        <td><strong>@(string.IsNullOrEmpty(item.UpdatedBy)?"- - - - -": item.UpdatedBy)</strong></td>
                        <td>
                            <div class="d-flex justify-content-center align-items-center">
                                <a class="btn btn-danger btn-delete-body mr-1" data-id="@item.Id">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                                <a class="btn btn-primary" asp-controller="LineType" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="far fa-edit"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    const bodiesEle = document.getElementById('body-bodies')

    const updateId = () => {
        const trEles = bodiesEle.querySelectorAll('tr')

        trEles.forEach((item, i) => {
            var th = item.querySelector('th')
            th.innerText = i + 1
        })
    }

    $('body').on('click', '.btn-delete-body', function () {
        const pw = window.prompt("Password?")

        if (pw.toLocaleLowerCase() !== '1234567890') {
            return
        }
        if (confirm('Bạn có chắc chắn muốn xóa LineType ?')) {
            if (confirm('Bạn có chắc chưa?')) {
                const id = $(this).data('id')

                $.ajax({
                    url: `/LineType/Delete/${id}`,
                    success: (res) => {
                        if (res.isSuccess) {
                            $(this).parents('tr').remove();
                            updateId()

                            alert('Xóa thành công')
                        }
                    }
                });


            }
        }
    })


</script>